# Generated by Django 5.2.3 on 2025-07-02 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(editable=False, help_text='Telegram username (without @).', max_length=256)),
                ('first_name', models.CharField(blank=True, default='', help_text='First name.', max_length=256)),
                ('last_name', models.CharField(blank=True, default='', help_text='Last name.', max_length=256)),
                ('tg_id', models.CharField(default='', help_text='Unique Telegram user ID as a string.', max_length=256, unique=True)),
                ('created_dt', models.DateTimeField(editable=False, help_text='Profile creation timestamp.')),
                ('modified_dt', models.DateTimeField(editable=False, help_text='Last modification timestamp.')),
                ('blocked_dt', models.DateTimeField(editable=False, help_text='Timestamp of blocking (if blocked).', null=True)),
                ('deleted_dt', models.DateTimeField(blank=True, help_text='Soft delete timestamp (if deleted).', null=True)),
                ('last_activity_dt', models.DateTimeField(editable=False, help_text='Timestamp of last user activity.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Linked Django user (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_dt'],
                'indexes': [models.Index(fields=['created_dt'], name='profiles_pr_created_60b2ad_idx')],
            },
        ),
    ]
